version: '3.8'

services:
  stupidrss:
    build: .
    container_name: stupidrss
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs:ro
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/rss_reader.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/app"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rss_data:
    driver: local
