services:
  stupidrss:
    build: .
    container_name: stupidrss
    ports:
      - "${PORT:-8000}:8000"
    volumes:
      - "${DATA_VOLUME_PATH:-./data}:${CONTAINER_DATA_PATH:-/app/data}"
    environment:
      - PYTHONPATH=${PYTHONPATH:-/app}
      - DATABASE_URL=${DATABASE_URL:-sqlite:///data/rss_reader.db}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  rss_data:
    driver: local
